name: macOS/Ubuntu CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build webserver
      run:  make PROD=1 && make fclean
